FROM golang:1.16.2 as build

ENV BIN_FILE "/opt/dialogs"
ENV CODE_DIR /go/src/

WORKDIR ${CODE_DIR}

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . ${CODE_DIR}

ARG LDFLAGS
RUN CGO_ENABLED=1 go build --tags dialogsservice\
        -ldflags "$LDFLAGS" \
        -o ${BIN_FILE} cmd/dialogs/main.go

CMD ${BIN_FILE}
