// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: dialog-servicev2.proto

package apiv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DialogsClient is the client API for Dialogs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DialogsClient interface {
	Dialogs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DialogsResponse, error)
}

type dialogsClient struct {
	cc grpc.ClientConnInterface
}

func NewDialogsClient(cc grpc.ClientConnInterface) DialogsClient {
	return &dialogsClient{cc}
}

func (c *dialogsClient) Dialogs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DialogsResponse, error) {
	out := new(DialogsResponse)
	err := c.cc.Invoke(ctx, "/dialogsv2.Dialogs/Dialogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DialogsServer is the server API for Dialogs service.
// All implementations must embed UnimplementedDialogsServer
// for forward compatibility
type DialogsServer interface {
	Dialogs(context.Context, *emptypb.Empty) (*DialogsResponse, error)
	mustEmbedUnimplementedDialogsServer()
}

// UnimplementedDialogsServer must be embedded to have forward compatible implementations.
type UnimplementedDialogsServer struct {
}

func (UnimplementedDialogsServer) Dialogs(context.Context, *emptypb.Empty) (*DialogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dialogs not implemented")
}
func (UnimplementedDialogsServer) mustEmbedUnimplementedDialogsServer() {}

// UnsafeDialogsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DialogsServer will
// result in compilation errors.
type UnsafeDialogsServer interface {
	mustEmbedUnimplementedDialogsServer()
}

func RegisterDialogsServer(s grpc.ServiceRegistrar, srv DialogsServer) {
	s.RegisterService(&Dialogs_ServiceDesc, srv)
}

func _Dialogs_Dialogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogsServer).Dialogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dialogsv2.Dialogs/Dialogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogsServer).Dialogs(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Dialogs_ServiceDesc is the grpc.ServiceDesc for Dialogs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dialogs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dialogsv2.Dialogs",
	HandlerType: (*DialogsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Dialogs",
			Handler:    _Dialogs_Dialogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dialog-servicev2.proto",
}
