{
 "title": "Dialogs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(otus_hl_dialogs_req_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(otus_hl_dialogs_error_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS by method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(method) (rate(otus_hl_dialogs_req_total[1m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "otus_hl_dialogs_req_total", "legendFormat": "{{method}}" }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "otus_hl_dialogs_error_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Percentile 0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(otus_hl_dialogs_latency_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request buckets",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (otus_hl_dialogs_latency_bucket)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}