// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: dialog-service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DialogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dialogs []*Dialog `protobuf:"bytes,1,rep,name=dialogs,proto3" json:"dialogs,omitempty"`
}

func (x *DialogsResponse) Reset() {
	*x = DialogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dialog_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogsResponse) ProtoMessage() {}

func (x *DialogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dialog_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogsResponse.ProtoReflect.Descriptor instead.
func (*DialogsResponse) Descriptor() ([]byte, []int) {
	return file_dialog_service_proto_rawDescGZIP(), []int{0}
}

func (x *DialogsResponse) GetDialogs() []*Dialog {
	if x != nil {
		return x.Dialogs
	}
	return nil
}

type DialogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DialogId int64 `protobuf:"varint,1,opt,name=dialogId,proto3" json:"dialogId,omitempty"`
}

func (x *DialogRequest) Reset() {
	*x = DialogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dialog_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogRequest) ProtoMessage() {}

func (x *DialogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dialog_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogRequest.ProtoReflect.Descriptor instead.
func (*DialogRequest) Descriptor() ([]byte, []int) {
	return file_dialog_service_proto_rawDescGZIP(), []int{1}
}

func (x *DialogRequest) GetDialogId() int64 {
	if x != nil {
		return x.DialogId
	}
	return 0
}

type DialogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dialog *Dialog `protobuf:"bytes,1,opt,name=dialog,proto3" json:"dialog,omitempty"`
}

func (x *DialogResponse) Reset() {
	*x = DialogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dialog_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogResponse) ProtoMessage() {}

func (x *DialogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dialog_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogResponse.ProtoReflect.Descriptor instead.
func (*DialogResponse) Descriptor() ([]byte, []int) {
	return file_dialog_service_proto_rawDescGZIP(), []int{2}
}

func (x *DialogResponse) GetDialog() *Dialog {
	if x != nil {
		return x.Dialog
	}
	return nil
}

type AddDialogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatorId int64  `protobuf:"varint,1,opt,name=creatorId,proto3" json:"creatorId,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AddDialogRequest) Reset() {
	*x = AddDialogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dialog_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDialogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDialogRequest) ProtoMessage() {}

func (x *AddDialogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dialog_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDialogRequest.ProtoReflect.Descriptor instead.
func (*AddDialogRequest) Descriptor() ([]byte, []int) {
	return file_dialog_service_proto_rawDescGZIP(), []int{3}
}

func (x *AddDialogRequest) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *AddDialogRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DialogAnswersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DialogId int64 `protobuf:"varint,1,opt,name=dialogId,proto3" json:"dialogId,omitempty"`
}

func (x *DialogAnswersRequest) Reset() {
	*x = DialogAnswersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dialog_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialogAnswersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogAnswersRequest) ProtoMessage() {}

func (x *DialogAnswersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dialog_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogAnswersRequest.ProtoReflect.Descriptor instead.
func (*DialogAnswersRequest) Descriptor() ([]byte, []int) {
	return file_dialog_service_proto_rawDescGZIP(), []int{4}
}

func (x *DialogAnswersRequest) GetDialogId() int64 {
	if x != nil {
		return x.DialogId
	}
	return 0
}

type DialogAnswersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answers []*DialogAnswer `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
}

func (x *DialogAnswersResponse) Reset() {
	*x = DialogAnswersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dialog_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialogAnswersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogAnswersResponse) ProtoMessage() {}

func (x *DialogAnswersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dialog_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogAnswersResponse.ProtoReflect.Descriptor instead.
func (*DialogAnswersResponse) Descriptor() ([]byte, []int) {
	return file_dialog_service_proto_rawDescGZIP(), []int{5}
}

func (x *DialogAnswersResponse) GetAnswers() []*DialogAnswer {
	if x != nil {
		return x.Answers
	}
	return nil
}

type AddDialogAnswerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DialogId  int64  `protobuf:"varint,1,opt,name=dialogId,proto3" json:"dialogId,omitempty"`
	CreatorId int64  `protobuf:"varint,2,opt,name=creatorId,proto3" json:"creatorId,omitempty"`
	Text      string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *AddDialogAnswerRequest) Reset() {
	*x = AddDialogAnswerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dialog_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDialogAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDialogAnswerRequest) ProtoMessage() {}

func (x *AddDialogAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dialog_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDialogAnswerRequest.ProtoReflect.Descriptor instead.
func (*AddDialogAnswerRequest) Descriptor() ([]byte, []int) {
	return file_dialog_service_proto_rawDescGZIP(), []int{6}
}

func (x *AddDialogAnswerRequest) GetDialogId() int64 {
	if x != nil {
		return x.DialogId
	}
	return 0
}

func (x *AddDialogAnswerRequest) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *AddDialogAnswerRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_dialog_service_proto protoreflect.FileDescriptor

var file_dialog_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x76,
	0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c,
	0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x0f,
	0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x28, 0x0a, 0x07, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67,
	0x52, 0x07, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x22, 0x2b, 0x0a, 0x0d, 0x44, 0x69, 0x61,
	0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69,
	0x61, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x69,
	0x61, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x22, 0x38, 0x0a, 0x0e, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x64, 0x69, 0x61, 0x6c,
	0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x69, 0x61, 0x6c, 0x6f,
	0x67, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x06, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67,
	0x22, 0x44, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x32, 0x0a, 0x14, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67,
	0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x15, 0x44, 0x69,
	0x61, 0x6c, 0x6f, 0x67, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x44, 0x69,
	0x61, 0x6c, 0x6f, 0x67, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x07, 0x61, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x73, 0x22, 0x66, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67,
	0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x32, 0xf5, 0x02, 0x0a, 0x07,
	0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x12, 0x3f, 0x0a, 0x07, 0x44, 0x69, 0x61, 0x6c, 0x6f,
	0x67, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1a, 0x2e, 0x64, 0x69, 0x61,
	0x6c, 0x6f, 0x67, 0x73, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x06, 0x44, 0x69, 0x61, 0x6c,
	0x6f, 0x67, 0x12, 0x18, 0x2e, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x76, 0x31, 0x2e, 0x44,
	0x69, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x64,
	0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x09, 0x41, 0x64, 0x64,
	0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x12, 0x1b, 0x2e, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73,
	0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x54, 0x0a,
	0x0d, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x12, 0x1f,
	0x2e, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f,
	0x67, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x61, 0x6c,
	0x6f, 0x67, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67,
	0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x21, 0x2e, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73,
	0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dialog_service_proto_rawDescOnce sync.Once
	file_dialog_service_proto_rawDescData = file_dialog_service_proto_rawDesc
)

func file_dialog_service_proto_rawDescGZIP() []byte {
	file_dialog_service_proto_rawDescOnce.Do(func() {
		file_dialog_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_dialog_service_proto_rawDescData)
	})
	return file_dialog_service_proto_rawDescData
}

var file_dialog_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_dialog_service_proto_goTypes = []interface{}{
	(*DialogsResponse)(nil),        // 0: dialogsv1.DialogsResponse
	(*DialogRequest)(nil),          // 1: dialogsv1.DialogRequest
	(*DialogResponse)(nil),         // 2: dialogsv1.DialogResponse
	(*AddDialogRequest)(nil),       // 3: dialogsv1.AddDialogRequest
	(*DialogAnswersRequest)(nil),   // 4: dialogsv1.DialogAnswersRequest
	(*DialogAnswersResponse)(nil),  // 5: dialogsv1.DialogAnswersResponse
	(*AddDialogAnswerRequest)(nil), // 6: dialogsv1.AddDialogAnswerRequest
	(*Dialog)(nil),                 // 7: dialog.Dialog
	(*DialogAnswer)(nil),           // 8: dialog.DialogAnswer
	(*emptypb.Empty)(nil),          // 9: google.protobuf.Empty
}
var file_dialog_service_proto_depIdxs = []int32{
	7, // 0: dialogsv1.DialogsResponse.dialogs:type_name -> dialog.Dialog
	7, // 1: dialogsv1.DialogResponse.dialog:type_name -> dialog.Dialog
	8, // 2: dialogsv1.DialogAnswersResponse.answers:type_name -> dialog.DialogAnswer
	9, // 3: dialogsv1.Dialogs.Dialogs:input_type -> google.protobuf.Empty
	1, // 4: dialogsv1.Dialogs.Dialog:input_type -> dialogsv1.DialogRequest
	3, // 5: dialogsv1.Dialogs.AddDialog:input_type -> dialogsv1.AddDialogRequest
	4, // 6: dialogsv1.Dialogs.DialogAnswers:input_type -> dialogsv1.DialogAnswersRequest
	6, // 7: dialogsv1.Dialogs.AddDialogAnswer:input_type -> dialogsv1.AddDialogAnswerRequest
	0, // 8: dialogsv1.Dialogs.Dialogs:output_type -> dialogsv1.DialogsResponse
	2, // 9: dialogsv1.Dialogs.Dialog:output_type -> dialogsv1.DialogResponse
	9, // 10: dialogsv1.Dialogs.AddDialog:output_type -> google.protobuf.Empty
	5, // 11: dialogsv1.Dialogs.DialogAnswers:output_type -> dialogsv1.DialogAnswersResponse
	9, // 12: dialogsv1.Dialogs.AddDialogAnswer:output_type -> google.protobuf.Empty
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_dialog_service_proto_init() }
func file_dialog_service_proto_init() {
	if File_dialog_service_proto != nil {
		return
	}
	file_dialog_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_dialog_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dialog_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dialog_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dialog_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDialogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dialog_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialogAnswersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dialog_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialogAnswersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dialog_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDialogAnswerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dialog_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dialog_service_proto_goTypes,
		DependencyIndexes: file_dialog_service_proto_depIdxs,
		MessageInfos:      file_dialog_service_proto_msgTypes,
	}.Build()
	File_dialog_service_proto = out.File
	file_dialog_service_proto_rawDesc = nil
	file_dialog_service_proto_goTypes = nil
	file_dialog_service_proto_depIdxs = nil
}
